### PR TITLE
Events ui

### PR DESCRIPTION
**Pull request by jeanjoe**
@KicaRonaldOkello @mulondo @kyakusahmed

Designed Index page and added the following features:
- Navigation bar
- Image
- Ticket booking Form
- Page Responsiveness

### CODE REVIEW

**Comment by jeanjoe** [comment]
Thanks @kaggwachristopher for your point, using the tag name globally means I want all the occurrences to share those properties, for this particular case I have set all images not to stretch beyond the parent border, so the maximum width of all images must fit within the specified parent element width i.e. All images can have varying width but the maximum width must not stretch beyond the parent element.

**Comment by mozzy22** [comment]
i think its cool now @jeanjoe

**Comment by jeanjoe** [comment]
Thanks @mozzy22 and @kaggwachristopher  for your time to review my work.

**Comment by alexkayabula** [comment]
Kaggwa is right but all in all its a good attempt

**Comment by mulondo** [comment]
that's great man. keep it up

**Comment by kaggwachristopher** [comment]
Welcome

**Pull request merged**
