### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by jeanjoe**
Tests for BookTicket for my Events UI.

### CODE REVIEW

**Comment by mozzy22** [comment]
thats good work @jeanjoe 
but i hvent seen any validation for a proper email adress ad may be empty name...u can correct me if am wrong ...probably u can ad a validation if u ddnt add one.

**Comment by jeanjoe** [comment]
Thanks @mozzy22 I will add that to increase my Tests.

**Comment by KicaRonaldOkello** [comment]
The work is good. But what if you added doc-strings to your methods instead of commenting them. Then you comment the lines of code instead

**Comment by kyakusahmed** [comment]
GOOD WORK FLOW

**Pull request merged**
