### PR TITLE
Python

### PR DESCRIPTION
**Pull request by jeanjoe**
@mozzy22 @alexkayabula

Review my reception.py code

### CODE REVIEW

**Comment by KicaRonaldOkello** [comment]
Good commit messages. I think you should make them a bit shorter. 
Eg. Add registration checker method. 
That would be descriptive enough

**Comment by alexkayabula** [comment]
Nice commits bro..... The project looks well implemented

**Comment by jeanjoe** [comment]
Thanks guys for your review

**Comment by mozzy22** [comment]
its a gud practice to squash the necesary commits into one , exampleu wud have squashed (merged) al the  python commits into one

**Pull request merged**
